<!-- 
FUNCTIONS :
fopen(): it is use to open the file .
1. we can access the file and any location of website (i.e., url).

syntax:
        fopen("name of file"or'',mode);
        mode:
        1. "w": stands for write .
        2. "w+"
        3. "r"
        4. "r+"
        5. "a" stand for append . by defaultly it writes only .
        6. "a+" for read and write its pointer position at last . 
        7. "x" creation
        8. "x+"

 -->