<!-- 
FUNCTIONS :
fopen(): it is use to open the file .
1. we can access the file and any location of website (i.e., url).

syntax:
        fopen("name of file"or'',mode);
        mode:
        1. "w": stands for write .
        2. "w+" it is for read and write 
        3. "r" it is only for reed 
        4. "r+" it is for read and write 
        5. "a" stand for append . by defaultly it writes only .
        6. "a+" for read and write its pointer position at last . 
        7. "x" creation and if file exists than it occurs an error.
        8. "x+" reading and writing if file exists than it occurs an error.
        9. fclose()
        10. file_size()
        11. fread()
        12. fwrite()
        13. fgets() it read one line at  time '
        14  feof() file end of . 
        15. fgetc () for character only 
        16. file_exists()
        17. unlink() - to deleting the file 
        18. copy (source file , destination)

 -->